server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/hytest?characterEncoding=utf-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    charset: utf-8
